Allow to write .bundle
https://github.com/ruby/actions/runs/8042603432?check_suite_focus=true#step:18:24
```
   There was an error while trying to write to
  `/home/runner/.bundle/cache/compact_index/rubygems.org.443.29b0360b937aa4d161703e6160654e47/info`.
  It is likely that you need to grant write permissions for that path.
  make: *** [uncommon.mk:1444: yes-test-bundler-prepare] Error 23
  Error: Process completed with exit code 2.
```