Ignore change of .bundle/cache
https://github.com/ruby/actions/runs/8142686093?check_suite_focus=true#step:19:32
```
+ diff -u /tmp/stat-before-tests.txt /tmp/stat-after-tests.txt
--- /tmp/stat-before-tests.txt	2022-09-01 18:49:01.856555819 +0000
+++ /tmp/stat-after-tests.txt	2022-09-01 19:09:03.677846745 +0000
@@ -4,7 +4,7 @@
 ["/home/runner/.bash_profile", "100644", 1, 1001, 122, 67, "bbc451426905c4a7b8d4f5ccf5b212d80141299d"]
 ["/home/runner/.bashrc", "100644", 1, 1001, 122, 3771, "c4d853993e323432cb84359de2c319b9a767b729"]
 ["/home/runner/.bundle", "40555", 3, 1001, 122, 4096, nil]
-["/home/runner/.bundle/cache", "40755", 2, 1001, 122, 4096, nil]
+["/home/runner/.bundle/cache", "40755", 3, 1001, 122, 4096, nil]
 ["/home/runner/.cargo", "40755", 4, 1001, 122, 4096, nil]
 ["/home/runner/.composer", "40755", 2, 1001, 122, 4096, nil]
 ["/home/runner/.config", "40555", 5, 1001, 122, 4096, nil]
Error: Process completed with exit code 1.
```