Update Gemfile*
ubuntu-latest changed from ubuntu-18.04 to ubuntu-20.04,
and failed to `bundle install`.

https://github.com/ruby/actions/runs/2015088965?check_suite_focus=true#step:4:5
```
/usr/lib/ruby/2.7.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by your /home/runner/work/actions/actions/tool/snapshot/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.3`
	from /usr/lib/ruby/2.7.0/rubygems.rb:294:in `activate_bin_path'
	from /usr/local/bin/bundle:23:in `<main>'
Error: Process completed with exit code 1.
```